/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.local.blockchain.views;

import com.local.blockchain.Bloque;
import com.local.blockchain.Cadena;
import com.local.blockchain.Transaccion;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class CadenaView extends javax.swing.JFrame {

    private Cadena cadena;

    public CadenaView(Cadena cadena) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.cadena = cadena;
        cargarBloques();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelBlockchain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setBackground(new java.awt.Color(255, 204, 51));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Estado Blockchain");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);

        panelBlockchain.setBackground(new java.awt.Color(255, 255, 255));
        panelBlockchain.setLayout(new javax.swing.BoxLayout(panelBlockchain, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(panelBlockchain);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel3)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarBloques() {
        String head = cadena.obtenerHeadMayor();
        Bloque bloque = cadena.obtenerBloque(head);

        while (bloque != null) {
            JPanel panel = new JPanel();
            panel.setBackground(Color.GRAY);
            panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
            JLabel hashAnteriorLabel = new JLabel("Hash Anterior: " + bloque.getHashAnterior());
            panel.add(hashAnteriorLabel);

            JLabel transaccionesLabel = new JLabel("Transacciones:");
            panel.add(transaccionesLabel);

            panel.add(new JLabel("---"));

            for (Transaccion transaccion : bloque.getTransacciones()) {
                JLabel idLabel = new JLabel("ID: " + transaccion.getId());
                panel.add(idLabel);

                JLabel emisorLabel = new JLabel("Emisor: " + transaccion.getEmisor());
                panel.add(emisorLabel);

                JLabel receptorLabel = new JLabel("Receptor: " + transaccion.getReceptor());
                panel.add(receptorLabel);

                JLabel montoLabel = new JLabel("Monto: " + transaccion.getCantidad());
                panel.add(montoLabel);

            }

            panel.add(new JLabel("---"));

            JLabel mineroLabel = new JLabel("Minero: " + bloque.getMinero());
            panel.add(mineroLabel);

            JLabel nonceLabel = new JLabel("Nonce: " + bloque.getNonce());
            panel.add(nonceLabel);

            JLabel hashLabel = new JLabel("Hash: " + bloque.getHash());
            panel.add(hashLabel);

            panel.add(new JLabel("")); // Espacio en blanco entre bloques
            panelBlockchain.add(panel);

            bloque = cadena.obtenerBloque(bloque.getHashAnterior());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBlockchain;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
