package com.local.blockchain.views;

import com.local.blockchain.Bloque;
import com.local.blockchain.Minero;
import com.local.blockchain.Nodo;
import com.local.blockchain.Sistema;
import com.local.blockchain.Transaccion;
import com.local.exepciones.FirmaException;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class MineroView extends javax.swing.JFrame {

    Minero minero;
    private boolean minando = false;
    private Timer timerMinado;
    private Timer timerData;

    public MineroView(Nodo nodo) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.minero = (Minero) nodo;
        setTitle("" + minero.getId());
        cartera.setText(minero.getDireccionCartera());
        buscarData();
    }

    public void detenerTimer() {
        if (timerMinado != null) {
            timerMinado.cancel();
        }
        if (timerData != null) {
            timerData.cancel();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        btnMinar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        consultarCadena = new javax.swing.JButton();
        estadoMinar = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelHistorialLog = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cartera = new javax.swing.JTextField();
        destinatario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        btnTransaccion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PanelHistorialTrans = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setBackground(new java.awt.Color(255, 204, 51));

        btnMinar.setBackground(new java.awt.Color(255, 153, 51));
        btnMinar.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btnMinar.setForeground(new java.awt.Color(0, 0, 0));
        btnMinar.setText("Empezar A Minar");
        btnMinar.setBorderPainted(false);
        btnMinar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Minero");

        consultarCadena.setBackground(new java.awt.Color(255, 153, 51));
        consultarCadena.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        consultarCadena.setForeground(new java.awt.Color(0, 0, 0));
        consultarCadena.setText("Consultar Cadena");
        consultarCadena.setBorderPainted(false);
        consultarCadena.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consultarCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCadenaActionPerformed(evt);
            }
        });

        estadoMinar.setBackground(new java.awt.Color(255, 0, 51));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);

        PanelHistorialLog.setBackground(new java.awt.Color(204, 204, 204));
        PanelHistorialLog.setLayout(new javax.swing.BoxLayout(PanelHistorialLog, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(PanelHistorialLog);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Consola (Log)");

        cartera.setEditable(false);
        cartera.setBackground(new java.awt.Color(255, 204, 51));
        cartera.setForeground(new java.awt.Color(0, 0, 0));
        cartera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cartera.setText("Eg13Hr8Rqd17o4QggkwhRA39NNE9KGcKznSkc2X1SnFu");
        cartera.setBorder(null);

        destinatario.setBackground(new java.awt.Color(255, 255, 255));
        destinatario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cartera del destinatario");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Monto");

        monto.setBackground(new java.awt.Color(255, 255, 255));
        monto.setForeground(new java.awt.Color(0, 0, 0));

        btnTransaccion.setBackground(new java.awt.Color(255, 153, 51));
        btnTransaccion.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btnTransaccion.setForeground(new java.awt.Color(0, 0, 0));
        btnTransaccion.setText("Hacer Transaccion");
        btnTransaccion.setBorderPainted(false);
        btnTransaccion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fondos");

        fondos.setBackground(new java.awt.Color(250, 250, 250));
        fondos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        fondos.setForeground(new java.awt.Color(0, 0, 0));
        fondos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondos.setText("0.00");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Mono", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Historial de transacciones");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        PanelHistorialTrans.setBackground(new java.awt.Color(204, 204, 204));
        PanelHistorialTrans.setLayout(new javax.swing.BoxLayout(PanelHistorialTrans, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane3.setViewportView(PanelHistorialTrans);

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addComponent(btnMinar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consultarCadena))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelContenedorLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel9))
                                    .addGroup(panelContenedorLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(btnTransaccion)))
                                .addGap(36, 36, 36))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGap(135, 135, 135)
                                    .addComponent(jLabel3))
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fondos, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelContenedorLayout.createSequentialGroup()
                                            .addGap(70, 70, 70)
                                            .addComponent(jLabel2))))
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGap(119, 119, 119)
                                    .addComponent(estadoMinar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel10))
                                .addGroup(panelContenedorLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(fondos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoMinar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinarActionPerformed
        if (minando) {
            estadoMinar.setBackground(Color.RED);
            minando = false;
            if (timerMinado != null) {
                timerMinado.cancel();
                logEnConsola("Minado detenido...");
            }
        } else {
            estadoMinar.setBackground(Color.GREEN);
            minando = true;
            empezarMinado(); // Llamar al método empezarMinado
        }

        estadoMinar.revalidate();
        estadoMinar.repaint();
    }//GEN-LAST:event_btnMinarActionPerformed

    private void consultarCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCadenaActionPerformed
        CadenaView cadenaV = new CadenaView(minero.getCadena());
        cadenaV.setVisible(true);
    }//GEN-LAST:event_consultarCadenaActionPerformed

    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed

        String receptor = destinatario.getText();
        String cantidad = monto.getText();

        if (receptor.isEmpty() || cantidad.isEmpty()) {
            mensajeEmergente("Llene todos los campos");
            return;
        }

        try {
            float cantidadInt = Float.parseFloat(cantidad);
            String msg = Sistema.getInstancia().propagarTransaccion(minero.crearTransaccion(receptor, cantidadInt));

            if (msg.isEmpty()) {
                mensajeEmergente("Transacción verificada y en proceso");
                return;
            }

            mensajeEmergente(msg);
        } catch (NumberFormatException ex) {
            mensajeEmergente("El monto debe ser numérico");
        } catch (FirmaException ex) {
        }

    }//GEN-LAST:event_btnTransaccionActionPerformed

    private void empezarMinado() {
        timerMinado = new Timer();
        logEnConsola("Empezando a minar...");

        TimerTask task = new TimerTask() {
            public void run() {
                Bloque bloque = minero.crearBloque();

                if (bloque == null) {
                    logEnConsola("En espera de suficientes transacciones");
                    return;
                }
                
                logEnConsola("Empezando a minar bloque...");
                Bloque resultado = minero.minarBloque(bloque);

                if (resultado != null) {
                    JOptionPane.showMessageDialog(null, "BLOQUE MINADO!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    String mensaje = "Nonce:" + resultado.getNonce() + " Hash:" + resultado.getHash();
                    logEnConsola(mensaje);
                }

            }
        };
        timerMinado.scheduleAtFixedRate(task, 0, 5000);
    }

    private void logEnConsola(String mensaje) {
        JLabel label = new JLabel(mensaje);
        PanelHistorialLog.add(label);
        PanelHistorialLog.revalidate();
        PanelHistorialLog.repaint();
    }

    private void mensajeEmergente(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }

    
    private void buscarData() {
        timerData = new Timer();
        ArrayList<Transaccion> transPropias = new ArrayList<>();
        ArrayList<Transaccion> transAmi = new ArrayList<>();
        String carteraDir = cartera.getText();

        TimerTask task = new TimerTask() {
            public void run() {
                String head = minero.getCadena().obtenerHeadMayor();
                Bloque bloque = minero.getCadena().obtenerBloque(head);
                transPropias.clear();
                transAmi.clear();

                while (bloque != null) {
                    for (Transaccion transaccion : bloque.getTransacciones()) {
                        if (carteraDir.equals(transaccion.getEmisor())) {
                            transPropias.add(transaccion);
                        } else if (carteraDir.equals(transaccion.getReceptor())) {
                            transAmi.add(transaccion);
                        }
                    }

                    bloque = minero.getCadena().obtenerBloque(bloque.getHashAnterior());
                }

                if (!transPropias.isEmpty() || !transAmi.isEmpty()) {
                    mostrarData(minero.getFondos(), transPropias, transAmi);
                }

                System.out.println("Buscando data minero: " + minero.getId());

            }
        };
        timerData.scheduleAtFixedRate(task, 0, 5000);
    }

    private void mostrarData(float fondosCantidad, ArrayList<Transaccion> transPropias, ArrayList<Transaccion> transAmi) {
        PanelHistorialTrans.removeAll();

        for (Transaccion trans : transPropias) {
            JLabel labelTrans = new JLabel(trans.getCantidad() + "$ -> " + trans.getReceptor());
            PanelHistorialTrans.add(labelTrans);
        }

        for (Transaccion trans : transAmi) {
            JLabel labelTrans = new JLabel(trans.getCantidad() + "$ <- " + trans.getReceptor());
            PanelHistorialTrans.add(labelTrans);
        }

        fondos.setText("" + fondosCantidad);
        fondos.revalidate();
        fondos.repaint();
        PanelHistorialTrans.revalidate();
        PanelHistorialTrans.repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelHistorialLog;
    private javax.swing.JPanel PanelHistorialTrans;
    private javax.swing.JButton btnMinar;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JTextField cartera;
    private javax.swing.JButton consultarCadena;
    private javax.swing.JTextField destinatario;
    private javax.swing.JProgressBar estadoMinar;
    private javax.swing.JLabel fondos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField monto;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
